import PeopleIcon from '@mui/icons-material/People';

export const mainNavbarItems = [
    {
        id: 0,
        icon: <PeopleIcon />,
        label: 'Recent',
        route: 'recent',
    },
    {
        id: 1,
        icon: <PeopleIcon />,
        label: 'AYS',
        route: 'ays',
    },
    {
        id: 2,
        icon: <PeopleIcon />,
        label: 'BGE',
        route: 'bge',
    },
    {
        id: 3,
        icon: <PeopleIcon />,
        label: 'BGW',
        route: 'bgw',
    },
    {
        id: 4,
        icon: <PeopleIcon />,
        label: 'MDC',
        route: 'mdc',
    },
    {
        id: 5,
        icon: <PeopleIcon />,
        label: 'MDN',
        route: 'mdn',
    },
    {
        id: 6,
        icon: <PeopleIcon />,
        label: 'MDS',
        route: 'mds',
    },
    {
        id: 7,
        icon: <PeopleIcon />,
        label: 'MGN',
        route: 'mgn',
    },
    {
        id: 8,
        icon: <PeopleIcon />,
        label: 'MGS',
        route: 'mgs',
    },
    {
        id: 9,
        icon: <PeopleIcon />,
        label: 'MHF',
        route: 'mhf',
    },
    {
        id: 10,
        icon: <PeopleIcon />,
        label: 'MNS',
        route: 'mns',
    },
    {
        id: 11,
        icon: <PeopleIcon />,
        label: 'MSM',
        route: 'msm',
    },
    {
        id: 12,
        icon: <PeopleIcon />,
        label: 'NPT',
        route: 'npt',
    },
    {
        id: 13,
        icon: <PeopleIcon />,
        label: 'NWA',
        route: 'nwa',
    },
    {
        id: 14,
        icon: <PeopleIcon />,
        label: 'SGE',
        route: 'sge',
    },
    {
        id: 15,
        icon: <PeopleIcon />,
        label: 'SGS',
        route: 'sgs',
    },
    {
        id: 16,
        icon: <PeopleIcon />,
        label: 'SHS',
        route: 'shs',
    },
    {
        id: 17,
        icon: <PeopleIcon />,
        label: 'TNY',
        route: 'tny',
    },
    {
        id: 18,
        icon: <PeopleIcon />,
        label: 'WEC',
        route: 'wec',
    },
    {
        id: 19,
        icon: <PeopleIcon />,
        label: 'WHH',
        route: 'whh',
    },
    {
        id: 20,
        icon: <PeopleIcon />,
        label: 'WWA',
        route: 'wwa',
    },
    {
        id: 21,
        icon: <PeopleIcon />,
        label: 'WWH',
        route: 'wwh',
    },
    {
        id: 22,
        icon: <PeopleIcon />,
        label: 'WWM',
        route: 'wwm',
    },
    {
        id: 23,
        icon: <PeopleIcon />,
        label: 'WWS',
        route: 'wws',
    },
    {
        id: 24,
        icon: <PeopleIcon />,
        label: 'WWT',
        route: 'wwt',
    },
    {
        id: 25,
        icon: <PeopleIcon />,
        label: 'YGE',
        route: 'yge',
    },
    {
        id: 26,
        icon: <PeopleIcon />,
        label: 'YGN',
        route: 'ygn',
    },
    {
        id: 27,
        icon: <PeopleIcon />,
        label: 'YGS',
        route: 'ygs',
    },
    {
        id: 28,
        icon: <PeopleIcon />,
        label: 'YGW',
        route: 'ygw',
    },

];